// packages/renderer/src/app/layout/output-panel/output-panel.component.ts
import {
  AfterViewChecked,
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  computed,
  inject,
  signal,
  viewChild,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatIconModule } from '@angular/material/icon';
import { MatTooltipModule } from '@angular/material/tooltip';
import type { LogEntry } from '@joinery/shared';
import { LogService } from '../../core/services/log.service';

type LevelFilter = 'all' | 'errors';

/**
 * Bottom-docked Output / Console panel. Shows the unified main+renderer log
 * timeline with an Errors-only toggle, per-entry expandable detail, copy, and
 * a link to reveal the on-disk log file. Opened from the status-bar badge or
 * the "Details" action on an error toast.
 */
@Component({
  selector: 'app-output-panel',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [CommonModule, MatIconModule, MatTooltipModule],
  template: `
    <div class="output-panel">
      <div class="op-header">
        <span class="op-title">Output</span>
        <div class="op-tabs">
          <button class="op-tab" [class.active]="filter() === 'all'" (click)="filter.set('all')">
            Log <span class="op-count">{{ logService.entries().length }}</span>
          </button>
          <button
            class="op-tab"
            [class.active]="filter() === 'errors'"
            (click)="filter.set('errors')"
          >
            Errors <span class="op-count error">{{ logService.errorCount() }}</span>
          </button>
        </div>
        <span class="op-spacer"></span>
        <button class="op-action" matTooltip="Reveal log file" (click)="logService.revealFile()">
          <mat-icon>folder_open</mat-icon>
        </button>
        <button class="op-action" matTooltip="Clear" (click)="logService.clear()">
          <mat-icon>delete_sweep</mat-icon>
        </button>
        <button class="op-action" matTooltip="Close (⌘J)" (click)="logService.close()">
          <mat-icon>close</mat-icon>
        </button>
      </div>

      <div #scroll class="op-body">
        @for (entry of visibleEntries(); track entry.id) {
          <div
            class="op-row"
            [class.error]="entry.level === 'error'"
            [class.warn]="entry.level === 'warn'"
            [class.focused]="entry.id === logService.focusedEntryId()"
            [attr.data-entry-id]="entry.id"
          >
            <div class="op-line" (click)="toggle(entry)">
              <mat-icon class="op-chevron" [class.open]="isExpanded(entry)" *ngIf="entry.detail">
                chevron_right
              </mat-icon>
              <span class="op-chevron-spacer" *ngIf="!entry.detail"></span>
              <span class="op-time">{{ entry.timestamp | date: 'HH:mm:ss.SSS' }}</span>
              <span class="op-level" [attr.data-level]="entry.level">{{ entry.level }}</span>
              <span class="op-tag">{{ entry.tag }}</span>
              <span class="op-msg">{{ entry.message }}</span>
              <button
                class="op-copy"
                matTooltip="Copy"
                (click)="copy(entry); $event.stopPropagation()"
              >
                <mat-icon>content_copy</mat-icon>
              </button>
            </div>
            @if (entry.detail && isExpanded(entry)) {
              <pre class="op-detail">{{ entry.detail }}</pre>
            }
          </div>
        } @empty {
          <div class="op-empty">No log entries yet.</div>
        }
      </div>
    </div>
  `,
  styles: [
    `
      .output-panel {
        display: flex;
        flex-direction: column;
        height: 100%;
        background: var(--bg-secondary);
        color: var(--text-primary);
        font-size: 12px;
      }
      .op-header {
        display: flex;
        align-items: center;
        gap: 8px;
        height: 30px;
        padding: 0 8px;
        border-bottom: 1px solid var(--border-primary);
        flex-shrink: 0;
      }
      .op-title {
        font-weight: 600;
        text-transform: uppercase;
        font-size: 11px;
        letter-spacing: 0.5px;
        color: var(--text-secondary);
      }
      .op-tabs {
        display: flex;
        gap: 2px;
        margin-left: 8px;
      }
      .op-tab {
        background: transparent;
        border: none;
        color: var(--text-secondary);
        padding: 2px 8px;
        cursor: pointer;
        border-radius: 4px;
        font-size: 12px;
      }
      .op-tab.active {
        background: var(--bg-tertiary);
        color: var(--text-primary);
      }
      .op-count {
        opacity: 0.7;
        font-variant-numeric: tabular-nums;
      }
      .op-count.error {
        color: var(--accent-error, #e5534b);
      }
      .op-spacer {
        flex: 1;
      }
      .op-action {
        background: transparent;
        border: none;
        color: var(--text-secondary);
        cursor: pointer;
        display: flex;
        align-items: center;
        padding: 2px;
        border-radius: 4px;
      }
      .op-action:hover {
        background: var(--bg-tertiary);
        color: var(--text-primary);
      }
      .op-action mat-icon {
        font-size: 16px;
        width: 16px;
        height: 16px;
      }
      .op-body {
        flex: 1;
        overflow-y: auto;
        font-family: var(--font-mono, monospace);
      }
      .op-row {
        border-bottom: 1px solid var(--border-subtle, rgba(127, 127, 127, 0.12));
      }
      .op-row.error {
        background: rgba(229, 83, 75, 0.08);
      }
      .op-row.warn {
        background: rgba(224, 168, 0, 0.07);
      }
      .op-row.focused {
        outline: 1px solid var(--accent-primary, #007acc);
        outline-offset: -1px;
      }
      .op-line {
        display: flex;
        align-items: center;
        gap: 6px;
        padding: 2px 8px;
        cursor: default;
        white-space: nowrap;
      }
      .op-chevron {
        font-size: 16px;
        width: 16px;
        height: 16px;
        transition: transform 0.1s ease;
        cursor: pointer;
      }
      .op-chevron.open {
        transform: rotate(90deg);
      }
      .op-chevron-spacer {
        width: 16px;
        flex-shrink: 0;
      }
      .op-time {
        color: var(--text-tertiary, #888);
        flex-shrink: 0;
      }
      .op-level {
        text-transform: uppercase;
        font-size: 10px;
        font-weight: 700;
        width: 42px;
        flex-shrink: 0;
      }
      .op-level[data-level='error'] {
        color: var(--accent-error, #e5534b);
      }
      .op-level[data-level='warn'] {
        color: var(--accent-warning, #e0a800);
      }
      .op-level[data-level='info'] {
        color: var(--accent-info, #4a9eff);
      }
      .op-level[data-level='debug'] {
        color: var(--text-tertiary, #888);
      }
      .op-tag {
        color: var(--text-secondary);
        flex-shrink: 0;
      }
      .op-msg {
        overflow: hidden;
        text-overflow: ellipsis;
        flex: 1;
      }
      .op-copy {
        background: transparent;
        border: none;
        color: var(--text-tertiary, #888);
        cursor: pointer;
        opacity: 0;
        display: flex;
        align-items: center;
        padding: 0;
      }
      .op-line:hover .op-copy {
        opacity: 1;
      }
      .op-copy mat-icon {
        font-size: 14px;
        width: 14px;
        height: 14px;
      }
      .op-detail {
        margin: 0;
        padding: 6px 8px 8px 38px;
        white-space: pre-wrap;
        word-break: break-word;
        color: var(--text-secondary);
        background: var(--bg-primary);
        font-size: 11px;
      }
      .op-empty {
        padding: 16px;
        color: var(--text-tertiary, #888);
        text-align: center;
      }
    `,
  ],
})
export class OutputPanelComponent implements AfterViewChecked {
  readonly logService = inject(LogService);

  readonly filter = signal<LevelFilter>('all');
  private readonly expandedIds = signal<Set<string>>(new Set());
  private readonly scroll = viewChild<ElementRef<HTMLDivElement>>('scroll');
  private lastFocusHandled: string | null = null;

  readonly visibleEntries = computed<LogEntry[]>(() => {
    const all = this.logService.entries();
    return this.filter() === 'errors' ? all.filter(e => e.level === 'error') : all;
  });

  ngAfterViewChecked(): void {
    // When opened with a focused entry (from an error toast), scroll to it once.
    const focusId = this.logService.focusedEntryId();
    if (focusId && focusId !== this.lastFocusHandled) {
      const el = this.scroll()?.nativeElement.querySelector(`[data-entry-id="${focusId}"]`);
      if (el) {
        el.scrollIntoView({ block: 'center' });
        this.lastFocusHandled = focusId;
        // Auto-expand the focused entry's detail.
        this.expandedIds.update(s => new Set(s).add(focusId));
      }
    }
  }

  isExpanded(entry: LogEntry): boolean {
    return this.expandedIds().has(entry.id);
  }

  toggle(entry: LogEntry): void {
    if (!entry.detail) return;
    this.expandedIds.update(s => {
      const next = new Set(s);
      if (next.has(entry.id)) next.delete(entry.id);
      else next.add(entry.id);
      return next;
    });
  }

  copy(entry: LogEntry): void {
    const text = `[${entry.level.toUpperCase()}] [${entry.tag}] ${entry.message}${
      entry.detail ? '\n' + entry.detail : ''
    }`;
    void navigator.clipboard?.writeText(text).catch(() => undefined);
  }
}

// packages/renderer-react/src/shell/workspace/output-panel.tsx
/**
 * The Output / Console panel: the unified main + renderer log timeline, an errors-only filter,
 * per-entry detail, copy, and a link that reveals the log file on disk.
 *
 * Ported from `packages/renderer/src/app/layout/output-panel/output-panel.component.ts` (321), with
 * two structural changes:
 *
 *  - **It is a Dockview panel, not a strip.** The Angular version was `height: 220px` in the
 *    shell's stylesheet (`shell.component.ts:181-186`) — not resizable, not movable, and the audit
 *    flagged it next to a sidebar that was both. Here it is a panel in a group below the tabs, so
 *    it resizes, docks anywhere, and its position is part of the persisted layout.
 *  - **Its header is Dockview's tab**, so the panel body carries only the filter and the actions.
 *    The Angular header re-implemented a tab strip inside a panel that was already inside a tab
 *    manager.
 *
 * The "scroll to the entry an error toast pointed at" behaviour is kept: `focusedEntryId` is set by
 * `logStore.open(id)` and cleared once honoured, which is the same one-shot the Angular
 * `ngAfterViewChecked` implemented with a `lastFocusHandled` field.
 */

import { useEffect, useMemo, useRef, useState } from 'react';
import { ChevronRight, Copy, FolderOpen, Trash2 } from 'lucide-react';
import type { LogEntry } from '@joinery/shared';

import { EmptyState, Icon, Tooltip, cn } from '../../ui';
import { logStore, useLogStore, selectErrorCount } from '../../state/logs';

type LevelFilter = 'all' | 'errors';

/** `HH:mm:ss.SSS`, the format the Angular template's `date` pipe produced. */
function formatTime(timestamp: number): string {
  const date = new Date(timestamp);
  const pad = (value: number, width = 2): string => String(value).padStart(width, '0');
  return `${pad(date.getHours())}:${pad(date.getMinutes())}:${pad(date.getSeconds())}.${pad(date.getMilliseconds(), 3)}`;
}

const LEVEL_CLASSES: Record<string, string> = {
  error: 'text-danger',
  warn: 'text-warning',
  // PROPOSAL §2.2: info is NOT blue. It is the muted foreground, and `text-info` resolves to it.
  info: 'text-info',
  debug: 'text-fg-subtle',
};

const ACTION_CLASSES = cn(
  'flex size-5 items-center justify-center rounded-xs border-0 bg-transparent text-fg-muted',
  'hover:bg-hover hover:text-fg',
  'focus-visible:outline-2 focus-visible:outline-offset-1 focus-visible:outline-focus'
);

const FILTER_CLASSES = cn(
  'flex h-5 items-center gap-1.5 rounded-xs border-0 bg-transparent px-2 text-xs text-fg-muted',
  'hover:bg-hover focus-visible:outline-2 focus-visible:outline-offset-1 focus-visible:outline-focus',
  'aria-pressed:bg-active aria-pressed:text-fg'
);

function LogRow({
  entry,
  expanded,
  focused,
  onToggle,
}: {
  readonly entry: LogEntry;
  readonly expanded: boolean;
  readonly focused: boolean;
  readonly onToggle: () => void;
}) {
  const hasDetail = typeof entry.detail === 'string' && entry.detail.length > 0;

  return (
    <div
      data-testid="output-row"
      data-entry-id={entry.id}
      data-level={entry.level}
      className={cn(
        'group border-b border-rule last:border-b-0',
        focused && 'outline-2 -outline-offset-2 outline-focus'
      )}
    >
      {/* A row is a button only when it has detail to disclose; a plain row is not interactive,
          so it gets no hover affordance either (interactivity.md). */}
      {hasDetail ? (
        <button
          type="button"
          aria-expanded={expanded}
          data-testid="output-row-toggle"
          onClick={onToggle}
          className={cn(
            'flex w-full items-center gap-1.5 border-0 bg-transparent px-2 py-0.5 text-left',
            'hover:bg-hover focus-visible:outline-2 focus-visible:-outline-offset-2 focus-visible:outline-focus'
          )}
        >
          <Icon
            icon={ChevronRight}
            size="sm"
            className={cn('stroke-fg-subtle transition-transform', expanded && 'rotate-90')}
          />
          <LogRowBody entry={entry} />
        </button>
      ) : (
        <div className="flex w-full items-center gap-1.5 px-2 py-0.5">
          <span aria-hidden="true" className="size-3.5 shrink-0" />
          <LogRowBody entry={entry} />
        </div>
      )}

      {hasDetail && expanded ? (
        <pre
          data-testid="output-row-detail"
          className="overflow-x-auto bg-surface px-2 py-1.5 pl-9 text-xs text-fg-muted"
        >
          {entry.detail}
        </pre>
      ) : null}
    </div>
  );
}

function LogRowBody({ entry }: { readonly entry: LogEntry }) {
  return (
    <>
      <span className="shrink-0 font-mono text-xs tabular-nums text-fg-subtle">
        {formatTime(entry.timestamp)}
      </span>
      <span
        className={cn(
          'w-10 shrink-0 font-mono text-2xs tracking-eyebrow uppercase',
          LEVEL_CLASSES[entry.level] ?? 'text-fg-muted'
        )}
      >
        {entry.level}
      </span>
      <span className="shrink-0 font-mono text-xs text-fg-muted">{entry.tag}</span>
      <span className="min-w-0 grow truncate font-mono text-xs text-fg">{entry.message}</span>
    </>
  );
}

export function OutputPanel() {
  const entries = useLogStore(state => state.entries);
  const errorCount = useLogStore(selectErrorCount);
  const focusedEntryId = useLogStore(state => state.focusedEntryId);
  const [filter, setFilter] = useState<LevelFilter>('all');
  const [expandedIds, setExpandedIds] = useState<ReadonlySet<string>>(() => new Set());
  const scrollRef = useRef<HTMLDivElement | null>(null);

  const visible = useMemo(
    () => (filter === 'errors' ? entries.filter(e => e.level === 'error') : entries),
    [entries, filter]
  );

  // Honour "scroll to this entry" once per id, then clear it — the store's flag is a request, not
  // state the panel should keep re-satisfying on every render.
  useEffect(() => {
    if (focusedEntryId === null) return;
    const row = scrollRef.current?.querySelector(`[data-entry-id="${focusedEntryId}"]`);
    if (!row) return;
    row.scrollIntoView({ block: 'center' });
    setExpandedIds(current => new Set(current).add(focusedEntryId));
    logStore.getState().clearFocus();
  }, [focusedEntryId, visible]);

  const toggle = (id: string): void =>
    setExpandedIds(current => {
      const next = new Set(current);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });

  const copy = (entry: LogEntry): void => {
    const text = `[${entry.level.toUpperCase()}] [${entry.tag}] ${entry.message}${
      entry.detail === undefined ? '' : `\n${entry.detail}`
    }`;
    void navigator.clipboard?.writeText(text).catch(() => undefined);
  };

  return (
    <div className="flex h-full min-h-0 flex-col bg-canvas" data-testid="output-panel">
      <div className="flex shrink-0 items-center gap-1 border-b border-rule px-2 py-1">
        <div role="group" aria-label="Log level" className="flex items-center gap-0.5">
          <button
            type="button"
            aria-pressed={filter === 'all'}
            data-testid="output-filter-all"
            onClick={() => setFilter('all')}
            className={FILTER_CLASSES}
          >
            Log <span className="tabular-nums text-fg-muted">{entries.length}</span>
          </button>
          <button
            type="button"
            aria-pressed={filter === 'errors'}
            data-testid="output-filter-errors"
            onClick={() => setFilter('errors')}
            className={FILTER_CLASSES}
          >
            Errors{' '}
            <span className={cn('tabular-nums', errorCount > 0 ? 'text-danger' : 'text-fg-muted')}>
              {errorCount}
            </span>
          </button>
        </div>

        <span className="grow" />

        <Tooltip content="Reveal the log file">
          <button
            type="button"
            aria-label="Reveal the log file"
            data-testid="output-reveal-file"
            onClick={() => logStore.getState().revealFile()}
            className={ACTION_CLASSES}
          >
            <Icon icon={FolderOpen} size="sm" />
          </button>
        </Tooltip>
        <Tooltip content="Clear the panel">
          <button
            type="button"
            aria-label="Clear the panel"
            data-testid="output-clear"
            onClick={() => logStore.getState().clear()}
            className={ACTION_CLASSES}
          >
            <Icon icon={Trash2} size="sm" />
          </button>
        </Tooltip>
      </div>

      <div ref={scrollRef} className="min-h-0 grow overflow-auto" data-testid="output-body">
        {visible.length === 0 ? (
          <div className="p-4">
            <EmptyState
              size="sm"
              title={filter === 'errors' ? 'No errors' : 'No log entries yet'}
              description={
                filter === 'errors'
                  ? 'Errors from the app and from this window will appear here.'
                  : 'The timeline shows entries from the main process and this window.'
              }
            />
          </div>
        ) : (
          visible.map(entry => (
            <div key={entry.id} className="group relative">
              <LogRow
                entry={entry}
                expanded={expandedIds.has(entry.id)}
                focused={entry.id === focusedEntryId}
                onToggle={() => toggle(entry.id)}
              />
              <button
                type="button"
                aria-label={`Copy ${entry.message}`}
                data-testid="output-row-copy"
                onClick={() => copy(entry)}
                className={cn(
                  ACTION_CLASSES,
                  'absolute top-0.5 right-1 opacity-0 group-hover:opacity-100 focus-visible:opacity-100'
                )}
              >
                <Icon icon={Copy} size="sm" />
              </button>
            </div>
          ))
        )}
      </div>
    </div>
  );
}
