// packages/renderer/src/app/shared/components/test-result-panel/test-result-panel.component.ts
/**
 * Inline failure panel for a connection Test: the error headline plus every
 * guidance line the main process returned. Renders nothing for null or
 * successful results, so hosts can bind their result signal directly. The
 * guidance list is height-capped and scrolls so a long list can never push
 * the host's action buttons off-screen.
 */

import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';
import { MatIconModule } from '@angular/material/icon';
import type { TestConnectionResult } from '@joinery/shared';

@Component({
  selector: 'app-test-result-panel',
  standalone: true,
  imports: [MatIconModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    @if (failure(); as result) {
      <div class="test-result-error" role="alert">
        <div class="test-result-header">
          <mat-icon>error_outline</mat-icon>
          <span>{{ result.error || 'Connection failed' }}</span>
        </div>
        @if (result.guidance?.length) {
          <ul>
            @for (g of result.guidance; track $index) {
              <li>{{ g }}</li>
            }
          </ul>
        }
      </div>
    }
  `,
  styles: [
    `
      :host {
        display: block;
      }

      /* When nothing renders (@if leaves only its comment anchor), collapse
         the host entirely so host-applied margins don't reserve blank space. */
      :host:empty {
        display: none;
      }

      .test-result-error {
        padding: 10px 12px;
        background: var(--error-bg, rgba(244, 67, 54, 0.1));
        border-left: 3px solid var(--status-error, #f44336);
        border-radius: 2px;
        font-size: 13px;
        line-height: 1.45;
        color: var(--text-primary);
        max-height: 200px;
        overflow-y: auto;

        .test-result-header {
          display: flex;
          align-items: center;
          gap: 8px;
          font-weight: 600;

          mat-icon {
            color: var(--status-error, #f44336);
            font-size: 18px;
            width: 18px;
            height: 18px;
            flex-shrink: 0;
          }
        }

        ul {
          margin: 6px 0 0;
          padding-left: 26px;
          color: var(--text-secondary);
          font-weight: 400;
        }
      }
    `,
  ],
})
export class TestResultPanelComponent {
  readonly result = input<TestConnectionResult | null>(null);

  readonly failure = computed(() => {
    const r = this.result();
    return r && !r.success ? r : null;
  });
}

// packages/renderer/src/features/connections/test-result-panel.tsx
/**
 * The inline failure panel for a connection **Test**: the error headline plus every guidance line
 * the main process returned.
 *
 * Ported from `shared/components/test-result-panel/test-result-panel.component.ts`. Renders nothing
 * for `null` or for a success, so a host can bind its result state directly — successes toast (the
 * connection store does it), failures render here, and nothing announces the same error twice.
 *
 * The guidance list is height-capped and scrolls, so a long list can never push the dialog's action
 * row off-screen. That cap is the reason this is a component rather than three lines inline: the
 * `AUTH_FAILED` category returns five guidance lines plus the password-hygiene diagnostic, which is
 * what `test-connection-feedback.spec.ts` asserts against a real MSSQL container.
 *
 * The guidance strings come from `packages/main`'s error categorisation and may name the password's
 * *length* but never its contents (`packages/shared/src/validators/password-hygiene.ts` header).
 * This component adds no text of its own.
 */

import { CircleAlert } from 'lucide-react';
import type { TestConnectionResult } from '@joinery/shared';

import { Icon, cn } from '../../ui';

export interface TestResultPanelProps {
  readonly result: TestConnectionResult | null;
  readonly className?: string;
}

export function TestResultPanel({ result, className }: TestResultPanelProps) {
  if (result === null || result.success) return null;

  return (
    <div
      // `role="alert"` here, unlike the hygiene banner's `status`: the user pressed Test and is
      // waiting for exactly this answer.
      role="alert"
      data-testid="connection-test-result"
      className={cn(
        'flex max-h-48 gap-2 overflow-y-auto rounded-sm border-l-2 border-danger bg-surface p-2 text-sm',
        className
      )}
    >
      <Icon icon={CircleAlert} size="sm" className="mt-px stroke-danger" />
      <div className="flex min-w-0 flex-col gap-1">
        <p data-testid="connection-test-error" className="text-fg text-pretty">
          {result.error === undefined || result.error === '' ? 'Connection failed' : result.error}
        </p>
        {result.guidance === undefined || result.guidance.length === 0 ? null : (
          <ul
            data-testid="connection-test-guidance"
            className="flex list-disc flex-col gap-1 pl-4 text-fg-muted"
          >
            {result.guidance.map(line => (
              <li key={line} className="text-pretty">
                {line}
              </li>
            ))}
          </ul>
        )}
      </div>
    </div>
  );
}
